version: "2.2"
services:
  jobmanager:
    image: pyflink:1.14.4-scala_2.11
    volumes:
      - .:/opt/wordcount
    ports:
      - "8081:8081"
    command: jobmanager
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager      

  taskmanager:
    image: pyflink:1.14.4-scala_2.11
    volumes:
      - .:/opt/pyflink-naive
    depends_on:
      - jobmanager
    command: taskmanager
    scale: 1
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
        taskmanager.numberOfTaskSlots: 2 